# 一、ndarray
## 1.ndarray 的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

5
arr的维度是: 0


In [3]:
arr = np.array([1,2,3])  # 创建1维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

[1 2 3]
arr的维度是: 1


In [4]:
arr = np.array([[1,2,3], [4,5,6]])  # 创建2维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度是: 2


### 同质性

In [5]:
arr = np.array([1,'hello'])  # 不同类型的元素会被强制转换为同一类型
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5])  # 不同类型的元素会被强制转换为同一类型
print(arr)

[1.  2.5]


## 2. ndarray的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
数组的类型： int64
元素的转置： 1


In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
数组的类型： float64
元素的转置： [1.  2.5 3. ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
数组的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的创建

In [10]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)  # 指定数据类型
print(arr.ndim)  # 属性和方法的区分：是否带括号，带括号的是方法，不带括号的是属性
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)  # 原始数组不变

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3), dtype = int)  # 创建一个2行3列的全0数组
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [13]:
arr = np.zeros((200,), dtype = int)  # 创建一个200行1列的全0数组
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
# 全1
arr = np.ones((5,8), dtype = int)  # 创建一个5行8列的全1数组
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [15]:
# 未初始化
arr = np.empty((4,3))  # 创建一个4行3列的未初始化数组，执行效率快
print(arr)

[[1.31228284e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 8.06630440e-308 2.92966904e-033]
 [4.71483083e-090 9.76836074e+165 1.55155023e+184]
 [9.95849747e-047 3.99910963e+252 2.32253274e-056]]


In [16]:
# 固定值
arr = np.full((3,4), 2026)  # 创建一个3行4列的全2026数组
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [17]:
arr1 = np.zeros_like(arr)  # 创建一个与arr形状相同的全0数组
print(arr1)
arr1 = np.empty_like(arr)  # 创建一个与arr形状相同的未初始化数组
print(arr1)
arr1 = np.ones_like(arr)  # 创建一个与arr形状相同的全1数组
print(arr1)
arr1 = np.full_like(arr, 2025)  # 创建一个与arr形状相同的全2025数组
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2656090036200                  50                   0
                    0]
 [  31244147616645120 4120349891991070059 3270516458839762277
  7090130557940611385]
 [7362600585106894132 3918748936486401889 8386112019185938739
  7233687420873831285]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [18]:
# 等差数列 2 4 6 8 10
arr = np.arange(2, 12, 2) # start, stop(不取), step
print(arr)

[ 2  4  6  8 10]


In [19]:
# 等间隔数列
arr = np.linspace(0, 100, 5)  # start, stop(取), num
print(arr)

[  0.  25.  50.  75. 100.]


In [20]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25, dtype=int)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base = 2, dtype=int) # 先把指数等间隔分布在0-4之间，然后以2为底取幂
print(arr)

[ 1  4 16]


In [22]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其余为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [23]:
# 对角矩阵：主对角线上是非0的数字，其余为0
arr = np.diag([1, 2, 3])  # 创建一个对角矩阵
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.4974305  0.00461739 0.7830449 ]
 [0.35404588 0.65308817 0.99276538]]


In [25]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2,3))  # 生成2行3列的随机浮点数，范围在3到6之间
print(arr)

[[3.71807012 3.88918494 4.92140544]
 [5.65113597 5.43057318 5.76969752]]


In [26]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2,3))  # 生成2行3列的随机整数，范围在3到30之间
print(arr)

[[ 5  9  6]
 [24 23  6]]


In [27]:
# 生成随机数列（正态分布，均值为0，标准差为1），基本在-3到3之间
# 两边概率小，中间概率大
arr = np.random.randn(2,3)  # 生成2行3列的随机数，服从标准正态分布
print(arr)

[[-0.92029395  0.6566202   0.00439262]
 [ 1.92088964  1.7643093   0.92341786]]


In [28]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
