# 一、ndarray
## 1.ndarray 的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5)  # 创建0维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

5
arr的维度是: 0


In [3]:
arr = np.array([1,2,3])  # 创建1维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

[1 2 3]
arr的维度是: 1


In [4]:
arr = np.array([[1,2,3], [4,5,6]])  # 创建2维ndarray数组
print(arr)
print('arr的维度是:', arr.ndim)  # 查看数组维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度是: 2


### 同质性

In [5]:
arr = np.array([1,'hello'])  # 不同类型的元素会被强制转换为同一类型
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5])  # 不同类型的元素会被强制转换为同一类型
print(arr)

[1.  2.5]


## 2. ndarray的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
数组的类型： int64
元素的转置： 1


In [8]:
arr = np.array([1, 2.5, 3])
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
数组的类型： float64
元素的转置： [1.  2.5 3. ]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状：', arr.shape)  # 查看数组形状 shape
print('数组的维度：', arr.ndim)  # 查看数组维度 number of dimensions
print('元素的个数：', arr.size)  # 查看数组元素个数 size
print('数组的类型：', arr.dtype)  # 查看数组元素类型 dtype
print('元素的转置：', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
数组的类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的创建

In [10]:
# 基础的创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)  # 指定数据类型
print(arr.ndim)  # 属性和方法的区分：是否带括号，带括号的是方法，不带括号的是属性
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)  # 原始数组不变

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((2,3), dtype = int)  # 创建一个2行3列的全0数组
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [13]:
arr = np.zeros((200,), dtype = int)  # 创建一个200行1列的全0数组
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
# 全1
arr = np.ones((5,8), dtype = int)  # 创建一个5行8列的全1数组
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [15]:
# 未初始化
arr = np.empty((4,3))  # 创建一个4行3列的未初始化数组，执行效率快
print(arr)

[[1.24098977e-311 2.81617418e-322 0.00000000e+000]
 [0.00000000e+000 1.00238459e-044 8.60952352e-072]
 [5.89592161e-091 2.09028226e-076 4.31925791e-038]
 [2.95005413e+179 6.48224659e+170 4.93432906e+257]]


In [16]:
# 固定值
arr = np.full((3,4), 2026)  # 创建一个3行4列的全2026数组
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [17]:
arr1 = np.zeros_like(arr)  # 创建一个与arr形状相同的全0数组
print(arr1)
arr1 = np.empty_like(arr)  # 创建一个与arr形状相同的未初始化数组
print(arr1)
arr1 = np.ones_like(arr)  # 创建一个与arr形状相同的全1数组
print(arr1)
arr1 = np.full_like(arr, 2025)  # 创建一个与arr形状相同的全2025数组
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[       2511791252696                   50                    0
                     0]
 [-8877107676052455424  3543889139687646571  3257007846182695728
   3474584481337454646]
 [ 4048002920101260643  7291947055385751605  8386112019186082104
   7004053313656484725]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [18]:
# 等差数列 2 4 6 8 10
arr = np.arange(2, 12, 2) # start, stop(不取), step
print(arr)

[ 2  4  6  8 10]


In [19]:
# 等间隔数列
arr = np.linspace(0, 100, 5)  # start, stop(取), num
print(arr)

[  0.  25.  50.  75. 100.]


In [20]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25, dtype=int)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base = 2, dtype=int) # 先把指数等间隔分布在0-4之间，然后以2为底取幂
print(arr)

[ 1  4 16]


In [22]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其余为0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [23]:
# 对角矩阵：主对角线上是非0的数字，其余为0
arr = np.diag([1, 2, 3])  # 创建一个对角矩阵
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [24]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.02061091 0.43839835 0.25956296]
 [0.20754105 0.19428111 0.26709997]]


In [25]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2,3))  # 生成2行3列的随机浮点数，范围在3到6之间
print(arr)

[[5.42902028 3.08913842 3.23199886]
 [3.58856351 4.22781491 4.17817465]]


In [26]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2,3))  # 生成2行3列的随机整数，范围在3到30之间
print(arr)

[[15 24 16]
 [22 17 24]]


In [27]:
# 生成随机数列（正态分布，均值为0，标准差为1），基本在-3到3之间
# 两边概率小，中间概率大
arr = np.random.randn(2,3)  # 生成2行3列的随机数，服从标准正态分布
print(arr)

[[-0.25285719 -1.51980947  0.75967096]
 [ 1.64061931  0.08520452  2.29182489]]


In [28]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray的数据类型

布尔类型 bool

整数类型 int unit

浮点数 float

复数 complex

In [29]:
arr = np.array([1, 0, 2, 0, -1], dtype= np.int8)  # 创建一个int8类型的ndarray数组
print(arr)
print(arr.dtype)


[ 1  0  2  0 -1]
int8


## 5. 索引与切片

In [30]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [31]:
print(arr[0])  # 索引第一个元素
print(arr[:])  # 获取全部的数据
print(arr[2:5])  # start:end+1 左闭右开区间
print(arr[slice(2, 15, 3)])  # start, end+1, step
print(arr[(arr>10) & (arr<70)])  # 布尔索引

17
[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  8 99]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [32]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [33]:
print(arr[1, 3])  # 索引第2行第4列的元素
print(arr[1, :])  # 获取第2行的所有数据
print(arr[1, 2: 5])  # 获取第2行的第3到第5个元素
print(arr[arr>50])
print(arr[2][arr[2]>50])  # 获取第3行大于50的元素
print(arr[:, 3])  # 获取第4列的所有元素

91
[17 19 80 91 60 72 76 30]
[80 91 60]
[76 78 80 91 60 72 76 64 79 94 79 95 71 53]
[64 79 94]
[19 91 79  4]


## 5. ndarray 的运算

In [34]:
# 数组之间的算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # 数组对应元素相加
print(a - b)  # 数组对应元素相减
print(a * b)  # 数组对应元素相乘
print(a / b)  # 数组对应元素相除
print(a ** 2)  # 幂运算

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [35]:
c = [1,2,3]
d = [4,5,6]
print(c + d)  # 列表直接相加是拼接，而不是对应元素相加
for i in range(len(c)):
    d[i] = c[i] + d[i]
print(d)  # 列表对应元素相加

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [36]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)  # 对应元素相加
print(a - b)  # 对应元素相减

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]


In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)  # 数组对应元素相加
print(a - b)  # 数组对应元素相减
print(a * b)  # 数组对应元素相乘
print(a / b)  # 数组对应元素相除
print(a ** 2)  # 幂运算

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [38]:
# 广播机制：1. 获取形状 2. 是否可以广播
# 同一维度，相同、1
a = np.array([1,2,3]) #1*3
b = np.array([[4],[5],[6]]) #3*1
print(a + b)  # 广播机制
print(b - a)
'''
a
1 2 3
1 2 3
1 2 3

b
4 4 4
5 5 5
6 6 6
'''


[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


'\na\n1 2 3\n1 2 3\n1 2 3\n\nb\n4 4 4\n5 5 5\n6 6 6\n'

In [39]:
# 不能被广播
# a = np.array([1,2,3]) #1*3
# b = np.array([4,5]) #1*2
# print(a + b)

In [40]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b) # 矩阵乘法

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [41]:
'''a
1 2 3
4 5 6
7 8 9
b
4 5 6
7 8 9
1 2 3

a1行 1 2 3
b1列 4 7 1
1*4 + 2*7 + 3*1 = 4 + 14 + 3 = 21
(1,2) a[1,] b[2,]
'''

'a\n1 2 3\n4 5 6\n7 8 9\nb\n4 5 6\n7 8 9\n1 2 3\n\na1行 1 2 3\nb1列 4 7 1\n1*4 + 2*7 + 3*1 = 4 + 14 + 3 = 21\n(1,2) a[1,] b[2,]\n'

# 二、 numpy 中的常用函数
## 1. 基本数学函数

In [42]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4,9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))  # 计算数组中每个元素的平方根

3.0
[1. 2. 3.]
[1. 5. 9.]


In [43]:
# 计算指数 e^x = y
print(np.exp(1)) # e的1次方

2.718281828459045


In [44]:
# 计算自然对数 ln y = x
print(np.log(2.718281828459045))

1.0


In [45]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [46]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [47]:
# 计算a的b次幂
print(np.power(arr, 2))

[1 1 4 9]


In [48]:
# 四舍五入
print(np.round([3.2, 4.51, 4.5, 8.1, 9.6])) # .5会向下舍入

[ 3.  5.  4.  8. 10.]


In [49]:
# 向上取整，向下取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))  # 向上取整
print(np.floor(arr))  # 向下取整

[ 2. 26. 82.]
[ 1. 25. 81.]


In [50]:
# 检测缺失值NaN
np.isnan([1, 2, np.nan, 3])

array([False, False,  True, False])

## 2. 统计函数

求和、平均值、中位数、标准差、方差

查找最大值、最小值

计算分位数、累积和、累积差

In [51]:
arr = np.random.randint(1,20,8)
print(arr)

[15  5 12  9  7 16 19 15]


In [52]:
# 求和
print(np.sum([1,2,3]))
print(np.sum(arr))

6
98


In [53]:
# 计算平均值
print(np.mean([1,2,3]))
print(np.mean(arr))

2.0
12.25


In [54]:
# 计算中位数
print(np.median([1,2,4,8]))
print(np.median(arr))

3.0
13.5


In [55]:
# 计算标准差、方差
print(np.var([1,2,3])) # 方差
print(np.std([1,2,3])) # 标准差

0.6666666666666666
0.816496580927726


In [56]:
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

1.375
1.375
0.234375
2.484375


In [57]:
# 计算最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[15  5 12  9  7 16 19 15]
19 6
5 1


In [58]:
# 分位数
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)
# _______________
# 44  47  64  67
print(np.median(arr))
print(np.percentile(arr, 25))
# 0.25 * 3 = 0.75
# (47-44)*0.75 + 44 = 46.25


[44 47 64 67]
55.5
46.25


In [59]:
# 累积和、累积积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 3. 比较函数

比较是否大于、小于、等于

逻辑与、或、非

检查数组中是否有一个True，是否所有都为True，自定义条件

In [60]:
# 是否大于
print(np.greater([3,4,5,6,7],4))
# 是否小于
print(np.less([3,4,5,6,7,8],4))
# 是否等于
print(np.equal([3,4,5,6,7,8],4))
print(np.equal([3,4,5],[4,4,4]))

[False False  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]


In [61]:
print(np.logical_and([1,0],[1,1]))
print(np.logical_not([1,0]))
print(np.logical_or([0,0],[1,0]))

[ True False]
[False  True]
[ True False]


In [62]:
# 检查元素是否至少有一个元素为True
print(np.any([0,1,0,0,0]))
print(np.any([0,0,0,0,0]))

# 检查是否全部元素为True
print(np.all([1,1]))
print(np.all([1,0]))

True
False
True
False


In [63]:
# 自定义条件
arr = np.array([1,2,3,4,5])
print(np.where(arr>3, arr, 0))  # 条件 符合条件 不符合条件

[0 0 0 4 5]


In [64]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3, 1, 0))

[1 1 0 0 0]


In [65]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score>=60, '及格', '不及格'))

[53 89 59 69 71 86 73 56 74 74 62 51 88 89 73 96 74 67 87 75]
['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [66]:
print(np.where(
    score<60, '不及格', np.where(
        score<80, '良好', '优秀'
    )
))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [67]:
# np.select(条件, 返回的结果)
print(np.select([score>80, (score>=60)&(score<=80),score<60], ['优秀', '良好', '不及格'], default = '未知'))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


## 4. 排序函数

In [68]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
# arr.sort()
# print(arr)
print(np.sort(arr))
print(np.argsort(arr))
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [69]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [70]:
# 数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [71]:
# 数组的分割
print(np.split(arr, 5))  # 必须能整除
print(np.split(arr, [6,12,18]))

[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [72]:
# 调整数组形状,必须能等分
print(np.reshape(arr, [4,5]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
