In [1]:
import numpy as np

In [9]:
temps = np.array([28,30,29,31,32,30,29])
print(temps)

print('平均气温')
print('%.3f'%np.mean(temps))
print('最高气温')
print(np.max(temps))
print('最低气温')
print(np.min(temps))

print('气温超过30的天数')
print(len(temps[temps>30]))

print(np.where(temps>30, 1, 0))
print(np.max(np.cumsum(np.where(temps>30, 1, 0))))

print(np.count_nonzero(temps>30))

[28 30 29 31 32 30 29]
平均气温
29.857
最高气温
32
最低气温
28
气温超过30的天数
2
[0 0 0 1 1 0 0]
2
2


In [16]:
score = np.array([85,90,78,92,88])
print(np.sort(score))

print('平均分：', np.mean(score))
print('中位数：', np.median(score))
print('标准差', '%.3f'%np.std(score))

print(score / 10)

[78 85 88 90 92]
平均分： 86.6
中位数： 88.0
标准差 4.883
[8.5 9.  7.8 9.2 8.8]


In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a + b)
print(a * b)

print(a @ b)
print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3,4))
print(arr)

print('每列的最大值', np.max(arr, axis=0)) # axis=0列 axis=1行
print('每行的最小值', np.min(arr, axis=1))

print(np.where(arr%2==1, -1, arr))

arr[arr%2==1] = -1
print(arr[1][2])

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值 [7 9 7 6]
每行的最小值 [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [40]:
arr = np.arange(1,13)
print(arr)
arr = np.reshape(arr, (3,4))
print(arr)
print('每行的和：', np.sum(arr, axis= 1))
print('每列的平均值', np.mean(arr, axis= 0))
print(np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [45]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])

arr[arr>10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [47]:
money = np.array([120,135,110,125,130,140])
print('总和', np.sum(money))
print('平均值', np.mean(money))
print('方差', np.var(money))

print('最高月份', np.argmax(money)+1)
print('最低月份', np.argmin(money)+1)

总和 760
平均值 126.66666666666667
方差 97.22222222222223
最高月份 6
最低月份 3


In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([a,b])
print(c)
print(np.reshape(c,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [57]:
arr = np.array([2,1,2,3,1,4,3])

u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

d = []
for i in range(len(u_arr)):
    d = d + [len(arr[arr==u_arr[i]])]
print(d)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [61]:
money = np.array([20,25,22,30,28])
a = np.array([15,18,16,22,20])
print('每天的利润', money-a)
b = money-a
print('利润的平均值', np.mean(b))
print('利润的标准差', np.std(b))
print('利润最高的天数', len(b[b==np.max(b)]))

每天的利润 [5 7 6 8 8]
利润的平均值 6.8
利润的标准差 1.16619037896906
利润最高的天数 2
